### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by vitobotta** [DarrenOfficial/dpaste#200]
Hi! It seems that a snippet can be deleted or edited by anyone I share it with. How can I prevent that?

Thanks

**Comment by DarrenOfficial** [comment]
You can't. dpaste is a place when you need to temporarily have someone look at a piece of code, due to legal reason & to prevent abuse, everyone can delete the snippets/paste.

If you want a place to put permanent snippets, check out [https://djangosnippets.org/](https://www.djangosnippets.org/).

*Sorry for the late response.*

**Comment by vitobotta** [comment]
Hi @DarrenOfficial thanks for getting back to me :) Will check out the project you mentioned, thanks!
