### ISSUE TITLE
Check-in about acceptable usage

### ISSUE THREAD

**Issue by beyarkay** [DarrenOfficial/dpaste#232]
## Description

Hey there! You might remember me from [this CORS issue](https://github.com/DarrenOfficial/dpaste/issues/225). Just want to say that it's been a life saver and super useful.

My use case is to upload a single file that's about 70kb and 600 lines, but I've got a user [who wants to use this on an ESP8266](https://github.com/beyarkay/eskom-calendar/issues/341) which is a little microcontroller that can connect to wifi, but it has basically no storage. Certainly not 70kb.

So we were thinking about splitting the file up into multiple parts, each about 2 lines long, and then my user can choose which one they want. So I'd end up uploading between 300 and 600 small CSV files, and this would happen about once every 5 days.

I just wanted to check in with you, ask how you're funding this project, and make sure this isn't being too cheeky? There are other solutions so it's not an issue if it's too much. Unfortunately the project I'm working on isn't funded, or I'd offer to help out with your costs ❤️.

**Comment by DarrenOfficial** [comment]
Hello there, 👋🏼 

> how you're funding this project

Straight from my wallet 🤣,

For hosting dPaste itself, I'm currently using FossHost https://web.archive.org/web/20230304224129/https://fosshost.org/ but due to some controversy that I frankly don't understand, apparently their CEO (Thomas) Went Poof
![discord](https://user-images.githubusercontent.com/55406094/230879183-f698d29f-dad7-45aa-ad1e-cc92b91dd695.png)


dpaste is still hosted on Fosshost, but I don't know how much longer it can be hosted there.
![aarch64 dashboard](https://user-images.githubusercontent.com/55406094/230878868-62fa95e5-d43b-406e-9713-1da8dc76a12c.png)
![specs](https://user-images.githubusercontent.com/55406094/230879520-b8bdba0a-1fa8-44b9-9ed9-c745684f3934.png)

With all things considered, monthly cost for this project isn't that big.

> make sure this isn't being too cheeky?

It should be alright, currently the database is 19G in size. And the use case your project use shouldn't be an issue… 

My future plan is to move it to a VPS of some sort.

> I'd offer to help out with your costs ❤️.

Feel free to do that via https://ko-fi.com/darrenofficial, I'd appreciate any sort of funding help

**Comment by beyarkay** [comment]
Okay thanks, sorry to hear about FossHost going poof. I'll keep you updated if I do end up using dpaste, although my user kinda needs a permanent URL so I might end up going with something else.

Regardless, thanks for the pastebin, it's been super helpful (and continues to be so).
